### ISSUE TITLE
Disable automatic population of "items"

### ISSUE THREAD

**Issue by hspitzley-czi** [losisin/helm-values-schema-json#129]
Hi there, is there a way to disable the automatic detection of items?

I have a values.yaml like this:
```yaml
defaults:
  # all fields defined here for the default schema
  name: default
  env: test

records: # @schema allOf: [{"type": "array"}, {"items": {"$ref": "#/properties/defaults"}}]
  - name: override
```

When I generate the schema I get this `values.schema.json`:
```json
{
  "$id": "argo.helm.charts/apps",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "defaults": {
      "properties": {
        "name": {
          "type": "string"
        },
        "env": {
          "type": "string"
        },
      "type": "object"
    },
    "records": {
      "allOf": [
        {
          "type": "array"
        },
        {
          "items": {
            "$ref": "#/properties/defaults"
          }
        }
      ],
      "items": {
        "properties": {
          "name": {
            "type": "string"
          },
        },
        "type": "object"
      }
    }
  },
  "title": "apps",
  "type": "object"
}
```

What I'm hoping for is a way to tell it to not put `items` within `records`, resulting in:
```json
...
    "records": {
      "allOf": [
        {
          "type": "array"
        },
        {
          "items": {
            "$ref": "#/properties/defaults"
          }
        }
      ],
    }
...
```

Since the inclusion of `"items": { "properties": { "name": { "type": "string" }, }, "type": "object" }` along with `additionalProperties: false` makes it so I can actually pass records with an `env` key

**Comment by losisin** [comment]
@hspitzley-czi it's not supported at this moment. you can only use `hidden: true` but that would remove the node completely from schema

**Comment by thefirstofthe300** [comment]
I think I'm looking for similar functionality.

Essentially, my use case looks is as follows:

1. Annotate our values file to have a single source of truth for individual chart values
2. Have globals schema which is the same across charts that has some empty defaults as part of the globals schema. The empty defaults make chart maintenance easier as we do not then need to handle nested null values.
3. Globals schema is referenced as a separate schema in the chart values file to help maintain a single source of truth for the globals schema.
4. Empty defaults, particularly objects which then overwrite sub-objects in the schema generation, cause schema validation to fail even though the globals schema has a proper definition for the sub object key/values.

I have tested that leaving the globals definition in our values schema like so
```yaml
...
    "global": {
      "$ref": "../../schemas/global.json",
      "type": "object",
      "additionalProperties": false
    },
...
```
does function as I'd expect. In this case, I'm thinking the entirety of the global section should be manually managed by us to prevent this problem.

Maybe in our case, it would be better to have a flag to ignore subvalues of when using a $ref?
