### ISSUE TITLE
$ref should always use allOf

### ISSUE THREAD

**Issue by jordan-da** [losisin/helm-values-schema-json#222]
According to the JSON Schema specification (including draft/2020-12), if a "$ref" keyword is present in an object, all other keywords in that same object (description, type, properties, etc.) are ignored. 

The example of:

```yaml
subchart: # @schema $ref: https://example.com/schema.json
  enabled: true
  name: subchart
  values:
    foo: bar
    bar: baz
```

Would basically never work as expected. I think we either need to always use `allOf` much like `--draft 7` does it, OR support:

```yaml
subchart: # @schema allOf: [{$ref: https://example.com/schema.json}, $self]
  enabled: true
  name: subchart
  values:
    foo: bar
    bar: baz
```

Clearly `$self` isn't the right keyword here but something like `.` or `$me` or whatever.

**Comment by applejag** [comment]
Also, I don't know which version of this plugin that you're using, but PR https://github.com/losisin/helm-values-schema-json/pull/212 (which was included in the v2.1.0 release) added this special case that when targeting draft 7 or below then it will wrap all non-`$ref` schema fields into a `allOf`

**Comment by jordan-da** [comment]
> After cross-referencing the spec, it seems using `$ref` and other fields on the same schema object is allowed in draft 2020-12:
> 
> > /.../ Note that this definition of how the results are determined means that other keywords can appear alongside of "$ref" in the same schema object.
> > https://json-schema.org/draft/2020-12/json-schema-core#name-direct-references-with-ref
> 
> Example in the spec that demos this: https://json-schema.org/draft/2020-12/json-schema-core#name-distinguishing-among-multip
> 
> And over in their docs they state this:
> 
> > [Draft-specific info]
> > In Draft 4-7, $ref behaves a little differently. When an object contains a $ref property, the object is considered a reference, not a schema. Therefore, any other properties you put in that object will not be treated as JSON Schema keywords and will be ignored by the validator. $ref can only be used where a schema is expected.
> > https://json-schema.org/understanding-json-schema/structuring#dollarref
> 
> So to my understanding, this plugin is already "working as intended". What use case do you have where this is an issue? [@jordan-da](https://github.com/jordan-da)

Oh maybe i misunderstood the spec, my apologies. 

As for my use case, I was trying to write some conditional logic in my helm chart. If something is `enabled` then "these 5 fields are required and can't be empty". Clearly it would be complicated for the plugin to support this natively, so i was gonna write out these complex schema augmentations in there own schema file, and then `$ref` them into main generated schema via the..

```
# @schema $ref: https://example.com/schema.json
```

... annotation. I _believe_ the trouble was having was I needed to use `allOf` in the top level values.yaml file so the system would resolve correctly. When mixing `$ref` and other fields together, it wasn't acting like an `and` when I thought it should?

That assumption seems to be false now though.

**Comment by applejag** [comment]
I'm not 100% following your use case, but if you get a reproducible of what you want the resulting schema to look like vs the actual output then we could perhaps look into fixing that.

Small aside regarding `required`: I've found using `required` to be a bad pattern because if you add the schema to a new values file using `# yaml-language-server: $schema=...` (that is meant to be used as `helm install -f ...`) then your editor doesn't account for the values already set in the chart's values.yaml file. Helm will lint the result of the chart's values.yaml file merged with the extra values file, but your editor won't. So I've found that `required` kind of messes up the editor developer experience.

**Comment by jordan-da** [comment]
Yeah I totally agree, we want to make sure the IDE doesn't get stupid and intelisense keeps working.

My use case is slightly different (sorry I had a hard time explaining it before):

If you have values that look like:

```yaml
serviceBob:
  enabled: false
  userName: ""
  password: ""
```

I want to make sure that if you flip `enabled` to `true`, that `userName` and `password` are marked as required. Clearly these aren't required if the service is disabled so I can't just always set them to required. The _only_ way I think I can manage this is by hand turning part of a my own scheme that used a json schema conditional to make those fields required if `enabled` is `true`, and then attached it to the `serviceBob` block over the top. That is where `allOf` I think comes into play. But I am not an expert, and I had trouble getting this to play nice honestly.

**Comment by AFMiziara** [comment]
I was trying to do exactly this also. It would be extremely helpful. Basically the problem here is if we have that for example:

```yaml
# application -- (object) Overall configuration for the application.
application: # @schema allOf: [{"$ref": "./schemas/custom/application.json"}]

  # application.name -- (string) The name of the application. This is used as a base name across all resources managed by the Chart.
  # @section -- Application
  name: # @schema type: string; required
```

The `$ref` on `application` top level field will simply override all the below definitions, instead of working as an `allOf`. The idea of the `./schemas/custom/application.json` in my case is also to add some conditional rules that are not supported here. I expected it to merge so I could also rely on the annotation on the fields.

**Comment by jordan-da** [comment]
So in general I do agree with you, but for this one point:

> It is generally much more preferred (and simpler) to add this type of logic to your Helm templates instead of your schemas to performs this validation. Such as via [`required`](https://helm.sh/docs/chart_template_guide/function_list/#required) or [`fail`](https://helm.sh/docs/chart_template_guide/function_list/#fail). Example:

I personally find it really difficult to apply this logic in the templates, esp if the same value is used multiple times (which we do... alot). Then you need to create helper files and add more over the top of template which can get hard to manage. 

Furthermore, if you are using json schema with your ide on the consuming side while writing values files (which I do, especially for really huge values files), you get red squiggles way before you ever run `helm` as your yaml is being validated as you write our your values. 

Again, this is all preference. I am not sure it makes sense for you to break your neck adding this support as there are other workaround for it. I am ok with closing this issue if you agree.

**Comment by applejag** [comment]
Hopefully #264 will fix your use cases when you're bundling schema files. It will be released in v2.3.0, once we get around to releasing that.

I'm closing this issue then. If any new improvement ideas come up then feel free to open a new issue.

**Comment by kitforbes** [comment]
@jordan-da, I use this pattern when I need to conditionally require values in a Helm chart:
```yaml
{{- with .Values.serviceBob }}
{{- if .enabled }}
{{- $_ := .userName | required ".serviceBob.userName must be set" -}}
{{- $_ := .password | required ".serviceBob.password must be set" -}}
apiVersion: v1
kind: Secret
metadata:
  name: service-bob
type: Opaque
data:
  username: {{ .userName | trim | quote }}
  password: {{ .password | trim | quote }}
{{- end }}
{{- end }}
```
You only need to include the "checks" in one of your files if you use the values in multiple locations. I find it a little cleaner than having multiple `required` calls.
