### ISSUE TITLE
multiple types not inferred when multiple values files are used

### ISSUE THREAD

**Issue by cornfeedhobo** [losisin/helm-values-schema-json#88]
If two values files are passed with the same block, but with different types:

```yaml
resources:
  requests:
    cpu: "100m"
```

```yaml
resources:
  requests:
    cpu: 100
```

The resulting schema type should become an array:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "resources": {
      "properties": {
        "cpu": {
          "type": ["string", "number"]
        }
      },
      "type": "object"
    }
  }
}
```
