### ISSUE TITLE
Schema entries not generated for two arrays with different items

### ISSUE THREAD

**Issue by TomasBahnik** [losisin/helm-values-schema-json#99]
using option `-noAdditionalProperties true`

the 2 records version reports `sync` and `ipAddr` are not allowed
```
data:
  search:
    - zone: www.google.com
      aliases: []
      records:
        - type: CNAME
          ttl: 300
          cnameOnlyExisting: true
          data:
            name: some.url.com
    - zone: some.url.com
      aliases: ['www.google.com','www.google.ad']
      records:
        - type: AAAA
          sync: true
          ttl: 300
          data:
            ipAddr: some.ip.address
```

while keeping just one

```
data:
  search:
#    - zone: www.google.com
#      aliases: []
#      records:
#        - type: CNAME
#          ttl: 300
#          cnameOnlyExisting: true
#          data:
#            name: some.url.com
    - zone: some.url.com
      aliases: ['www.google.com','www.google.ad']
      records:
        - type: AAAA
          sync: true
          ttl: 300
          data:
            ipAddr: some.ip.address
```
generates both `sync` and `ipAddr`

```
                            "records": {
                                "items": {
                                    "additionalProperties": false,
                                    "properties": {
                                        "data": {
                                            "additionalProperties": false,
                                            "properties": {
                                                "ipAddr": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "sync": {
                                            "type": "boolean"
                                        },
                                        "ttl": {
                                            "type": "integer"
                                        },
                                        "type": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "type": "array"
                            },
```

When you revert the order

```
data:
  search:
    - zone: some.url.com
      aliases: [ 'www.google.com','www.google.ad' ]
      records:
        - type: AAAA
          sync: true
          ttl: 300
          data:
            ipAddr: some.ip.address
    - zone: www.google.com
      aliases: [ ]
      records:
        - type: CNAME
          ttl: 300
          cnameOnlyExisting: true
          data:
            name: some.url.com
```
`cnameOnlyExisting` and `name` become not allowed.
